### ISSUE TITLE
Add EOF Calculation to METcalcpy for Stratosphere and Weather Regime

### ISSUE THREAD

**Issue by CPKalb** [dtcenter/METcalcpy#127]
## Describe the New Feature ##
Currently, EOFs exist in several places in METcalcpy and METplus.  EOFs are computed as part of the Weather regime use case and exist in metcalcpy/contributed/blocking_weather_regime/WeatherRegime.py.  They are also calculated as part of Stratosphere QBO, and are located in METplus/parm/use_cases/model_applications/UserScript_fcstGFS_obsERA_StratosphereQBO/stratosphere_qbo_driver.py.  Finally, the RMM and OMI use cases accept EOFs that have been previously computed and are stored in files, but currently there is not a way to compute EOFs for them. 

This issue addresses putting the EOF calculation in a common location rather than having it in the two locations for Weather Regime and Stratosphere QBO.  This will include modifying the weather regime calculation in METcalcpy to use the new EOFs, which should be straightforward.  The Stratosphere QBO use case will require a more substantial modification to point to this new version of EOFs, since the EOF calculation is part of the driver script in METplus.  This will have to be modified as part of a separate issue in METplus (an issue for this does not currently exist).

One of the things to note here is that the weather regime use case expects EOF input as numpy arrays, while the Stratosphere use case expects input as Xarrays.  This new EOF calculation will hopefully handle both of these data types.

It also might make sense to add the option to write an output file that could be used for the RMM and OMI use cases.  

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
I'm guessing maybe 2 days to add the calculation and possibly a little more if file writing is added. 

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] Add EOF calculation
- [ ] Update Weather Regime Calculation to use this new EOF
- [ ] Add option to write EOFs to an output file if we decide to do this

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
