### ISSUE TITLE
Confirm Event Equalization for off-setting initializations still works

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/METcalcpy#16]
## Describe the Task ##
There an anomolous model in the NCEP production suite - SREF - that runs at 03,09,15,21 UTC as opposed to the standard cadence of 00,06,12,18 UTC.  Back in the early 2010s, event equalization worked so that a +3 UTC offset SREF could be compared directly to the other operational models at the same valid times.  

We need to confirm that METcalcpy still has that capability and it produces the same results.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Review code to make sure it is available in METcalcpy*
- [ ] *Identify database to use - Maybe HWT 2011 unless DTC has a more recent on*
- [ ] *Run in METviewer*
- [ ] *Run in METcalcpy*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2791541 - when it becomes active

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the task and verify your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by TatianaBurek** [comment]
The functionality was tested with XML and it works.
[plot_20201214_131625.xml.txt](https://github.com/dtcenter/METcalcpy/files/5691404/plot_20201214_131625.xml.txt)
