### ISSUE TITLE
Create a Contributor's Guide

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METcalcpy#178]
## Describe the New Feature ##
Create documentation for contributing to the METcalcpy repository.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
@lisagoodrich, when you're finished with the METplotpy work, please Sphinx-ify the index.rst file into multiple chapters using a new branch with this issue number because it looks like the branch may have already been deleted.  Feel free to use a new branch name or the same one that previously existed (I think it was feature_178_contributors_guide).

**Comment by lisagoodrich** [comment]
Hello @fisherhucar and @bikegeek, 
I'm going through my open github issues and I'm wondering if this one can be closed/changed.  
The Contributors Guide has been created: https://metcalcpy.readthedocs.io/en/latest/Contributors_Guide/index.html#
Since we are no longer manually building this anymore, this section needs to be changed: 
https://metcalcpy.readthedocs.io/en/latest/Contributors_Guide/index.html#create-user-documentation 
I'm ccing @jprestop because she likes to be kept in the the loop.
Thanks!

**Comment by jprestop** [comment]
@lisagoodrich, @fisherhucar, @bikegeek 

> Since we are no longer manually building this anymore, this section needs to be changed:
https://metcalcpy.readthedocs.io/en/latest/Contributors_Guide/index.html#create-user-documentation

It seems like we could just direct users to this page: [Read the Docs METplus Documentation ](https://metplus.readthedocs.io/en/latest/Contributors_Guide/documentation.html#read-the-docs-metplus-documentation)

**Comment by bikegeek** [comment]
This is not true for METcalcpy or METplotpy.  There is no .build_docs.py
script in these repositories.

Regards,
Minna
---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Research Applications Lab
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by jprestop** [comment]
@bikegeek 
> This is not true for METcalcpy or METplotpy.  There is no .build_docs.py script in these repositories.

.build_docs.py is only referenced in Section 10.7 [Building Sphinx Documentation Manually](https://metplus.readthedocs.io/en/latest/Contributors_Guide/documentation.html#building-sphinx-documentation-manually), but Contributors shouldn't have to build the docs manually, so I thought we could refer them to Section 10.6  [Read the Docs METplus Documentation ](https://metplus.readthedocs.io/en/latest/Contributors_Guide/documentation.html#read-the-docs-metplus-documentation).  Will that not work?

**Comment by bikegeek** [comment]
You are correct.  I just looked at the METplotpy Contributor's Guide and it
refers contributors to look at the docs generated as a result of a push.
Go ahead and remove the originally intended text.  I (as developer) usually
manually build to verify that there aren't any syntax errors/formatting
errors in the documentation before committing.

Thanks,
Minna
---------------
Minna Win
Pronouns: she/her
National Center for Atmospheric Research
Research Applications Lab
Developmental Testbed Center
Phone: 303-497-8423
Fax:   303-497-8401
---------------

**Comment by jprestop** [comment]
@lisagoodrich let me know if you have any questions about these changes.

@bikegeek 
> I (as developer) usually manually build to verify that there aren't any syntax errors/formatting errors in the documentation before committing.

Oh, wow, that is kind of you, but please don't feel like you have to do that. The switch to RTD was supposed to save you the hassle of doing that by building your feature branch for you.
