### ISSUE TITLE
Move METcalcpy repository from the NCAR to DTCenter organization.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METcalcpy#18]
## Describe the Task ##

Move the METcalcpy repository from the NCAR organization to the DTCenter organization. The GitHub URL needs to be updated in few locations:
```
egrep -i  "github.com\/NCAR"  `find ./ -type f` | cut -d":" -f1 | sort -u
.//.github/ISSUE_TEMPLATE/bug_report.md
.//.github/ISSUE_TEMPLATE/enhancement_request.md
.//.github/ISSUE_TEMPLATE/new_feature_request.md
.//.github/ISSUE_TEMPLATE/task.md
.//setup.py
```

### Time Estimate ###
2 hours.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
No sub-issues required.

### Relevant Deadlines ###
None

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: John Halley Gotway
- [X] Select **scientist(s)** or **no scientist** required: No scientist required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)
This change does not affect the other repositories, but similar changes will be required in those repos.

## Task Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the task and verify your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [] Iterate until the reviewer(s) accept and merge your changes.
- [] Delete your fork or branch.
- [] Close this issue.
