### ISSUE TITLE
Vertical field interpolation with pressure and height coordinates.

### ISSUE THREAD

**Issue by dwfncar** [dtcenter/METcalcpy#20]
*Replace italics below with details for this issue.*

## Describe the New Feature ##
Create a python module for vertical interpolation of fields
between grids with pressure and height coordinates.

Initial version will read a single NetCDF file and write a single NetCDF file,
and use the python xarray module.
Pressure to height conversion will be the only vertical coordinate conversion
initially implemented.
MetPy will be used for the physics routines.

The next version will support input file lists
and GRIB format with the pygrib.

### Acceptance Testing ###
*List input data types and sources.*
Initial version: test on a MERRA2 inst3_3d_asm_Np datasets (Fillmore),
test on TCRMW output (Fillmore)
GRIB version: test on GRIB dataset (Biswas)

*Describe tests required for new functionality.*
Read a list of fields from the YAML config file.
Interpolate fields on isobaric coordinate surfaces onto constant height coordinate surfaces.
Note the MetPy physics can be verified with the inst3_3d_asm_Np by replicating
the geopotential height fields.

### Time Estimate ###
*Estimate the amount of work required here.*
Initial version 3 days.

### Account Key ###
2785041

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [x] YAML config file
- [x] Layer thickness physics with MetPy
- [ ] Vertical interpolation with xarray
- [x] NetCDF I/O
- [ ] GRIB I/O

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
David Fillmore
- [ ] Select **scientist(s)** or **no scientist** required
Mrinal Biswas

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**
NASA, DTC

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
This example and some of the functionality from MetPy may (or may not) be useful:
https://unidata.github.io/MetPy/latest/examples/sigma_to_pressure_interpolation.html#sphx-glr-examples-sigma-to-pressure-interpolation-py
