### ISSUE TITLE
Create coordinate converter for [0,360] to [-180,180]

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METcalcpy#21]
## Describe the Task ##
Create a utility to convert longitudes that range from 0 to 360 to those that range from -180 to 180 (ie West-East).  Read in a numpy array or  list of longitudes and return a numpy list of longitudes.  Use the formula lon_west_east = ((lon_360 + 180.0) % 360.0 ) - 180.0 where '%' is the modulo operator.  

### Time Estimate ###
*Estimate the amount of work required here.*
This should take  one day including writing tests.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] Create the feature branch from the develop branch
- [x] Add a function to the util/utils.py module
- [x] Write parametrized unit test in pytest

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** Minna Win
- [x] Select **scientist(s)** Tina Kalb

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [x] Complete the task and verify your changes.
- [x] Add/update unit tests.
- [ ] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop** and link the pull request to this issue.
Pull request: `feature <Issue Number> <Description>`
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
