### ISSUE TITLE
Transition Calculation of the Difficulty Index to METcalcpy

### ISSUE THREAD

**Issue by lindsayrblank** [dtcenter/METcalcpy#27]
## Describe the New Feature ##
The DTC is working with Liz Satterfield and Bill Campbell of the NRL to transition the Difficulty Index to METcalcpy. NRL has provided the python code to calculate and plot the Difficulty Index.

Here is a description of the Difficulty Index from NRL:
"The overall aim of this work is to graphically represent the expected difficulty of a decision based on a set of forecasts (ensemble) of, e.g., significant wave height as a function of space and time. There are two basic factors that can make a decision difficult. The first factor is the proximity of the ensemble mean forecast to a decision threshold, e.g. 12ft seas. If the ensemble mean is either much lower or much higher than the threshold, the decision is easier; if it is closer to the threshold, the decision is harder. The second factor is the forecast precision, or ensemble spread. The greater the spread around the ensemble mean, the more likely it is that there will be ensemble members both above and below the decision threshold, making the decision harder. (A third factor that we will not address here is undiagnosed systematic error, which adds uncertainty in a similar way to ensemble spread.) The challenge is combing these factors into a continuous function that allows the user to assess relative risk."

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*
Successfully ran provided NRL scripts "out of the box" on eyewall. 

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*
This work will take 3 full days of work. 

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [x] Stage NRL scripts in METcalcpy
- [x] Take out plotting portions of scripts to be used in METplotpy
- [x] Pare down script to just final version of Difficulty Index
- [x] Make sure code is formatted correctly
- [x] Create unit test
- [x] Test functionality 

### Relevant Deadlines ###
November 30

### Funding Source ###
2700021

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required: Minna Win (for guidance)
- [X] Select **scientist(s)** or **no scientist** required: Lindsay Blank

### Labels ###
- [x] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.
