### ISSUE TITLE
Update METplus Analysis tools to handle TC-RMW modifications in MET version 11.1.0

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METcalcpy#308]
## Describe the Enhancement ##
While doing development for TC-Diag in dtcenter/MET#2681, @JohnHalleyGotway made some deliberate changes to the NetCDF output from the TC-RMW tool. These are described in dtcenter/MET#2523 and merged into the develop branch of MET in PR dtcenter/MET#2524. It was decided that keeping the structure of the NetCDF output from TC-RMW and TC-Diag consistent is desirable, and so the TC-Diag requirements drove these changes. This task is to update the METplus Analysis tools to accommodate them. My guess is that this will only require changes in METplotpy to plot the TC-RMW output. However, change *might* be needed in METcalcpy and METdataio either in addition or instead of METplotpy. Please move or duplicate this issue in those repos as needed.

Compare the following files on **seneca** to see the diffs:
Old output file:
`/d1/projects/MET/MET_regression/main_v11.0/NB20230524/MET-main_v11.0/test_output/tc_rmw/tc_rmw_pressure_lev_out.nc`
New output file:
`/d1/projects/MET/MET_regression/develop/NB20230524/MET-develop/test_output/tc_rmw/tc_rmw_pressure_lev_out.nc`

The differences simply change the order of the dimensions for all gridded variables from `(range, azimuth, track_point)` to `(track_point, range, azimuth)`. So instead of the time dimension being last, it is now first.

In addition, unmerged development in the `feature_2168_tc_diag` branch of MET will fix a bug in the definition of the azimuths. The existing code divides 360 degrees by `n-1` when it should simply be `n`. This will change the azimuth values in the NetCDF output from `0, 2.01117318435754, 4.02234636871508, 6.03351955307263, ...` to `0, 2, 4, 6, ...`. I don't expect that to cause any plotting issues. Its just an additional difference to be aware of.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
TC-Diag project (2770043)

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: @bikegeek 
- [x] Select **scientist(s)** or **no scientist** required: @KathrynNewman to test updated plotting code

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
