### ISSUE TITLE
Make sure all existing tests are working

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METcalcpy#65]
## Describe the Task ##
Make sure that all tests in the METcalcpy/test directory are working (ie no failures or error messages)

### Time Estimate ###
*Estimate the amount of work required here.*
~1-2 days, depending on the number of tests that are no longer working.

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [x] *test_agg_stats_and_boot* **See comment below**
- [x] *test_calc_difficulty_index*
- [x] *test_compare_images*
- [x] *test_convert_lon_indices*
- [x] *test_event_equalize*
- [x] *test_event_equalize_against_values* **See comments below**
- [x] *test_convert_lon_indices*
- [x] *test_lon360_to_180*
- [x] *test_statistics*
- [x] *test_tost_paired*
- [x] *test_utils*
- [x] *test_validate_mv_python*
### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
Split 2791541, 2712231, 2799991

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [ ] Add/update documentation.
- [x] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by bikegeek** [comment]
### **test_agg_stats_and_boot.py**

- 1 test fails 
- 6 tests  pass
-  tests take on order of 30+ minutes to run

**Comment by bikegeek** [comment]
### **test_event_equalize_against_values.py**

- FileNotFoundError dut to missing file, ee_av_input.data
- test needs to be updated with data available in METcalcpy/test/data 
- directory to input data, etc in tests should be updated to reflect correct location of test data

**Comment by bikegeek** [comment]
### **Difficulty Index**

- "accepted" plot, provided by NRL is no longer a 100% match with the plot generated by the test
- The title font appearance is the only difference from the "accepted" plot
- The comparison.mssim value is 0.9926... rather than 1, which reflects a perfect match
- sent email to Lindsay to determine how to proceed:
- contact NRL and see if this change in title font is acceptable, and then modify assert to check for comparison.mssim value greater than 0.99 (more than 99% match)

**Comment by TatianaBurek** [comment]
I fixed issues with test_agg_stats_and_boot and test_event_equalize_against_values
