### ISSUE TITLE
Provide support to sort a dataframe of CTC data by fcst_thresh values

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METcalcpy#75]
*Replace italics below with details for this issue.*

## Describe the Task ##
*Create a method that will take as input a pandas dataframe that contains CTC data and sort it based on the fcst_thresh values in the fcst_thresh column.  Allow sorting to be done in either ASCENDING or DESCENDING order. This is part of the METplotpy issues 11, 81, and 85 (and is necessary for these three issues): 

- https://github.com/dtcenter/METplotpy/issues/11
- https://github.com/dtcenter/METplotpy/issues/81
- https://github.com/dtcenter/METplotpy/issues/85

### Time Estimate ###
*Estimate the amount of work required here.*
*1 to 1 1/2 days*

### Sub-Issues ###
Consider breaking the task down into sub-issues.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)**  Minna Win
- [x] Select **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging. NA
- [x] Add/update unit tests.
- [x] Add/update documentation. NA
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
