### ISSUE TITLE
Set up METcalcpy docs to use Github Actions

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METcalcpy#80]
## Describe the Task ##
Set up this repository to use Github actions to generate documentation.  

## Follow these instructions:
1. create a METcalpy/docs/_build directory
2. under the .github directory, create a workflows directory
3. cd to the workflows directory
4. Get the main.yml file via wget (or use curl if on a Mac):

- _curl -O https://raw.githubusercontent.com/dtcenter/METplus/feature_github_actions_doc/.github/workflows/main.yml_
5. modify the main.yml file by changing the METplus repo name to METcalcpy
6. Close the main.yml file and commit
7. cd to the METcalcpy/docs directory and edit the Makefile by finding the Makefile target and prepending the original instructions with:

- _[ -d $(BUILDDIR) ] || mkdir -p $(BUILDDIR)_
8. Append the following to the end of the original instructions:

-  _-w "$(BUILDDIR)/warnings.log"_
9. Close the Makefile and commit changes
10. cd to METcalcpy/docs directory and open the conf.py file
11. remove the two lines with html_theme_options:

- html_theme_options = {'canonical_url': 'https://dtcenter.github.io/METcalcpy/latest/'}
- html_theme_options['versions'] = {'latest': '../latest', 'develop': '../develop'}
12. close file and commit changes

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** Minna Win
- [x] Select **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
