### ISSUE TITLE
Add goodness distance calculation for performance diagram

### ISSUE THREAD

**Issue by jvigh** [dtcenter/METcalcpy#86]
## Add goodness distance calculation for performance diagram ##
The goal of this issue is to compute the Euclidean distance between the location of a particular set of probabilistic forecasts and the upper right-hand corner of the performance diagram. As long as the bias is within a range that is acceptable to the sponsor, this Euclidean distance represents a key aspect of the "goodness" of the forecast (high POD and high CSI/low FAR). These distances should be saved to output for later use in other performance evaluation tools such as scorecards. For additional background, see: https://docs.google.com/presentation/d/1cbPaF75E441OW_1LVahJUox6UrjlhPheEbjLfI9GOiI/edit#slide=id.p

### Acceptance Testing ###
Prioritized in the following order (high to low):
- RI evaluation data from Jonathan’s HFIP-PREDICT project (GRIP, FHLO, etc.)
- TC genesis evaluation data from Dan Halperin’s TC genesis project (ask John Halley Gotway)
- RI data from Paul’s Ensemble RI project (lots of ensemble data)
- JTWC forecast and model data (1997-2021) 

*Describe tests required for new functionality.*

### Time Estimate ###
1 days

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
Tara and Jonathan need to have a recorded presentation with results by April 30.
If we get it done by May 28, it could go into RC1.

### Funding Source ###
Use account key 2785041 (NOAA Hur Supp 1A-3-5 METplus) for time spent on this development. 

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] This will directly impact METcalcpy. A separate issue will be defined for related development in METplotpy. A METplus will also be developed.

- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
