### ISSUE TITLE
Add the code to compute RMM and OMI to METcalcpy

### ISSUE THREAD

**Issue by CPKalb** [dtcenter/METcalcpy#89]
## Describe the New Feature ##
Convert the scripts by Maria Gehne into METCalcpy.  The script with RMM and OMI calculations is located here: https://github.com/dtcenter/METcalcpy/blob/feature_mjo_indices/metcalcpy/contributed/tropical_diagnostics/compute_mjo_indices.py.  I'm not sure if read_omi_eofs and read_rmm_eofs functions should go in METcalcpy or somewhere else in METplus.  Also, we probably need to change the read_omi_eofs.py and read_rmm_eofs.py so that the input data files are not hard coded :-/

### Acceptance Testing ###
data is on kiowa:/d1/projects/METcalcpy/METcalcpy_Data/MJO_Indices
These scripts will be called from a driver script in METplus issue 892

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ]

### Relevant Deadlines ###
As soon as possible

### Funding Source ###
2785051

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [ ] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [ ] [METplus Issue](https://github.com/dtcenter/METplus/issues/892)
- [ ] [METplotpy Issue](https://github.com/dtcenter/METplotpy/issues/109)

## New Feature Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
