### ISSUE TITLE
Return status from functions like BasePlot.save_to_file

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/METcalcpy#90]
While debugging a new METplus use case that runs a script to generate a Hovmoeller diagram (dtcenter/METplus#626) calling METcalcpy, I discovered that the use case would run successfully but not generate any output images. The log file mentioned that the file could not be created, but there were no errors.

## Describe the Enhancement ##
Enhance the functions that catch failures to return some values (True/False, path/None, etc.) so that the calling functions can check this value to determine if the function succeeded or not. It would also be nice if the error was more clear that it is an error, i.e. the line starts with "ERROR:" or something similar.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [X] Select **milestone** to next major version milestone or "Future Versions"

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] Update the METplus use cases that call METcalcpy accordingly

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hankenstein2** [comment]
Will create a method to create this ERROR message that we can call in other places if wanted and can add to save to file later

**Comment by hankenstein2** [comment]
This is actually an issue for METplotpy and I will open it and close it there. We have added some error messages to both base_plot and hovmoeller.py
